apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scoreboard
  labels:
    app: scoreboard
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: scoreboard
