apiVersion: v1
kind: Service
metadata:
  name: scoreboard
  labels:
    app: scoreboard
spec:
  type: {{ .Values.service.type }}
  selector:
    app: scoreboard
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
