/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ScoreEvents {
  action_id: string;
  created_at: Generated<Timestamp>;
  delta: number;
  id: Generated<string>;
  user_id: string;
}

export interface UserScores {
  last_action_id: string | null;
  total_score: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DB {
  score_events: ScoreEvents;
  user_scores: UserScores;
}
